### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [compute-io/fliplr#1]
Open question: for functions like `fliplr`, should a view based approach or a memory reset approach be used? Or should an option be provided to specify which one a consumer prefers?

**Comment by Planeshifter** [comment]
Everything works as expected, code looks fine. With regards to above question, I don't know. I guess the question is whether the cost of re-allocating memory is high enough to warrant the added complexity of supporting both approaches?

**Comment by kgryte** [comment]
Granted. Of course, if complexity does not reside here, it must reside somewhere. Matter of deciding who bears the burden of handling the complexity. 

For now, we can punt this and address it down the road. If consumers want a hard reset, we should be able to support such a use case by adding a non-breaking option. Will open an issue to revisit this in the future.
